### ISSUE TITLE
sdmx transform v1

### ISSUE THREAD

**Issue by mikeAdamss** [ONSdigital/dp-data-pipelines#12]
## What is this

We need a transform that can take an SDMX file and return two path objects.

- 1 to a csv
- 1 to a json metadata file

## What to do

`dp-data-pipelines/shared/transforms/sdmx/v1.py`

```python
def sdmx_transform_v1(sdmx: Path) -> Tuple[Path, Path]:
    """
    Taking a Path to an sdmx file, create a csv and a json
    metadata file and return paths to them.

    return: csv_path, metadata_path
    """
    ...
```

## Acceptance Criteria

- [ ] function written
- [ ] tests written

**Comment by MartynBSpooner** [comment]
Just some notes:
Code branching for SDMX version builds - need a logical approach to address differences in SDMX version inputs etc.
Logging / notification integration.
Longer term meta data push / drop for basic UI of all pipelines - lists, last successful run / failure etc.

**Comment by MartynBSpooner** [comment]
From J earlier:
"I suppose we'll need something to compare the final output to the input to check the transform has been done correctly
also, depending on whether it'll be implemented the same, we'll need a way to determine is a dataset is a new version/edition of an existing one and adjust the metadata as needed
we could also do with someone writing some form of validation step for the inputs (though this will vague as we dont have a final structure for the config file), this could also be tied into the end csv validation (if we already check over the input file we might as well capture some details from it, expected number of observations for example)"

**Comment by MartynBSpooner** [comment]
Note: current transform protos are to what we know as SDMX v2.0.
v2.1 was notably different.

**Comment by MartynBSpooner** [comment]
J:
Code proto is a first build, non-optimized - needs refactoring etc.
Code the integration with the pipeline steps Mike has outlined
Methods to check the SDMX version (could probably do this by checking what tags are being used, but might need some more examples to ensure they're consistent within each version)
Code will need the error messages coded in, so throwing a bunch of try/except stuff so the messages sent out are a bit more informative etc.

**Comment by MartynBSpooner** [comment]
Signature / interface documentation - maybe linked to config file(s).

**Comment by mikeAdamss** [comment]
done
